/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param items New items to add to cart
 * @param trackingData Tracking data
 */

data class AddItemsCartRequest (
    /* New items to add to cart */
    @field:Json(name = "items")
    val items: kotlin.collections.List<AddItemsCartRequestItems>,
    /* Tracking data */
    @field:Json(name = "tracking_data")
    val trackingData: kotlin.Any? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

