/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models



import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * Emoji tags data
 * @param data Category data in text or hex encoded formats
 * @param hash Hash identifies record, can be used to delete records
 * @param tag Category as a hex string number
 */

data class EidResponseResult (
    /* Category data in text or hex encoded formats */
    @SerializedName( "data")
    val data: kotlin.String,
    /* Hash identifies record, can be used to delete records */
    @SerializedName( "hash")
    val hash: kotlin.String,
    /* Category as a hex string number */
    @SerializedName( "tag")
    val tag: kotlin.String
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

