/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models



import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param description 
 * @param finishDate 
 * @param key Counter object
 * @param metric Counter type
 * @param startDate 
 * @param value Counter value
 */

data class EmojiStatsResponseMetrics (
    @SerializedName( "description")
    val description: kotlin.String,
    @SerializedName( "finish_date")
    val finishDate: java.time.OffsetDateTime,
    /* Counter object */
    @SerializedName( "key")
    val key: kotlin.String,
    /* Counter type */
    @SerializedName( "metric")
    val metric: kotlin.String,
    @SerializedName( "start_date")
    val startDate: java.time.OffsetDateTime,
    /* Counter value */
    @SerializedName( "value")
    val value: kotlin.Long
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

