/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models



import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param totalUses 
 * @param activator 
 * @param available 
 * @param codeType 
 * @param createdAt 
 * @param deletedAt 
 * @param discountAsPercentage 
 * @param discountInCents 
 * @param endDate 
 * @param id 
 * @param maxEmojisPerUser 
 * @param maxUses 
 * @param name 
 * @param organizationId 
 * @param pattern 
 * @param redemptionCode 
 * @param startDate 
 * @param updatedAt 
 */

data class ListOfCodeAvailabilityData (
    @SerializedName( "total_uses")
    val totalUses: kotlin.Long,
    @SerializedName( "activator")
    val activator: ListOfCodeAvailabilityData.Activator? = null,
    @SerializedName( "available")
    val available: kotlin.Long? = null,
    @SerializedName( "code_type")
    val codeType: ListOfCodeAvailabilityData.CodeType? = null,
    @SerializedName( "created_at")
    val createdAt: java.time.OffsetDateTime? = null,
    @SerializedName( "deleted_at")
    val deletedAt: java.time.OffsetDateTime? = null,
    @SerializedName( "discount_as_percentage")
    val discountAsPercentage: kotlin.Int? = null,
    @SerializedName( "discount_in_cents")
    val discountInCents: kotlin.Int? = null,
    @SerializedName( "end_date")
    val endDate: java.time.OffsetDateTime? = null,
    @SerializedName( "id")
    val id: java.util.UUID? = null,
    @SerializedName( "max_emojis_per_user")
    val maxEmojisPerUser: kotlin.Int? = null,
    @SerializedName( "max_uses")
    val maxUses: kotlin.Int? = null,
    @SerializedName( "name")
    val name: kotlin.String? = null,
    @SerializedName( "organization_id")
    val organizationId: java.util.UUID? = null,
    @SerializedName( "pattern")
    val pattern: kotlin.Any? = null,
    @SerializedName( "redemption_code")
    val redemptionCode: kotlin.String? = null,
    @SerializedName( "start_date")
    val startDate: java.time.OffsetDateTime? = null,
    @SerializedName( "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
    * 
    * Values: redemptionCode,secretKey
    */
    
    enum class Activator(val value: kotlin.String){
        @SerializedName( "RedemptionCode") redemptionCode("RedemptionCode"),
        @SerializedName( "SecretKey") secretKey("SecretKey");
    }
    /**
    * 
    * Values: discount,randomYat
    */
    
    enum class CodeType(val value: kotlin.String){
        @SerializedName( "Discount") discount("Discount"),
        @SerializedName( "RandomYat") randomYat("RandomYat");
    }
}

