/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models


import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * For Admin: Expanded Lootbox Type
 * @param config 
 * @param createdAt The timestamp for when this loot box type was created
 * @param description A more detailed description of the loot box type
 * @param id The loot box type id
 * @param name The name of this loot box type
 */

data class ListOfPublicLootBoxLootboxType (
    @SerializedName( "config")
    val config: ListOfPublicLootBoxLootboxTypeConfig,
    /* The timestamp for when this loot box type was created */
    @SerializedName( "created_at")
    val createdAt: java.time.OffsetDateTime,
    /* A more detailed description of the loot box type */
    @SerializedName( "description")
    val description: kotlin.String,
    /* The loot box type id */
    @SerializedName( "id")
    val id: java.util.UUID,
    /* The name of this loot box type */
    @SerializedName( "name")
    val name: kotlin.String
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

