/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models


import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param features Enabled features for the user
 * @param globalScopes A list of fine-grained permissions the user may perform.
 * @param organizationRoles The role this user has in each organisation. Organisations are currently not used, but are reserved for  future operations.
 * @param organizationScopes The scopes that are granted to this user for each organisation. Organisations are currently not used, but are  reserved for future operations.
 * @param pendingTransfers List of transfers pending acceptance on current user side
 * @param pubkeys A list of this user's public keys. When yats are deployed to the blockchain, users prove ownership of their  Yats with digital signatures, proving knowledge of the private keys that \"own\" the yat. In the centralised  implementation of Yat, the server will custody the users' wallets and private keys, but in other respects the  ownership model is the same.
 * @param role The role assigned to this user. Roles grant authority to user accounts to perform certain actions.
 * @param user 
 * @param everflowTransactionId transaction id indicating if the user signed up from a partner via everflow redirect
 */

data class LoadUserCurrentUser (
    /* Enabled features for the user */
    @SerializedName( "features")
    val features: kotlin.collections.List<CurrentUserFeatures>,
    /* A list of fine-grained permissions the user may perform. */
    @SerializedName( "global_scopes")
    val globalScopes: List<LoadUserCurrentUser.GlobalScopes>,
    /* The role this user has in each organisation. Organisations are currently not used, but are reserved for  future operations. */
    @SerializedName( "organization_roles")
    val organizationRoles: kotlin.collections.Map<kotlin.String, kotlin.String>,
    /* The scopes that are granted to this user for each organisation. Organisations are currently not used, but are  reserved for future operations. */
    @SerializedName( "organization_scopes")
    val organizationScopes: kotlin.collections.Map<kotlin.String, kotlin.collections.List<kotlin.String>>,
    /* List of transfers pending acceptance on current user side */
    @SerializedName( "pending_transfers")
    val pendingTransfers: kotlin.collections.List<kotlin.String>,
    /* A list of this user's public keys. When yats are deployed to the blockchain, users prove ownership of their  Yats with digital signatures, proving knowledge of the private keys that \"own\" the yat. In the centralised  implementation of Yat, the server will custody the users' wallets and private keys, but in other respects the  ownership model is the same. */
    @SerializedName( "pubkeys")
    val pubkeys: kotlin.collections.List<kotlin.String>,
    /* The role assigned to this user. Roles grant authority to user accounts to perform certain actions. */
    @SerializedName( "role")
    val role: LoadUserCurrentUser.Role,
    @SerializedName( "user")
    val user: CurrentUserUser,
    /* transaction id indicating if the user signed up from a partner via everflow redirect */
    @SerializedName( "everflow_transaction_id")
    val everflowTransactionId: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
    * A list of fine-grained permissions the user may perform.
    * Values: adminCartUpdate,adminEmojiDestroy,adminEmojiLoad,adminEmojiRegister,adminEmojiTransfer,adminEmojiUpdateFeatures,adminEmojiUpdateSecureData,adminEmojiWrite,adminFeatureUserRead,adminInvitesWrite,adminInvitesList,adminLootboxRead,adminLootboxWrite,adminNotificationsWrite,adminUserBypass2fa,adminUserLoad,adminUserLoginAs,adminUserTwoFactorAuthDestroy,adminUserRoleUpdate,cartShow,cartUpdate,codeDelete,codeRead,codeWrite,userCreateApiKey,domainActionRead,domainEventRead,editionDelete,editionRead,editionWrite,emojiGroupsDelete,emojiGroupsRead,emojiGroupsWrite,emojiTransfer,featureDelete,featureRead,featureWrite,lootboxUse,orderPaymentOverride,orderRead,orderReadSelf,orderRefund,orderRefundOverride,orderResendConfirmation,organizationAdmin,organizationCodeAdmin,organizationEmojiList,organizationEmojiWrite,organizationListRead,organizationRead,organizationUserAdmin,organizationUserRead,organizationWrite,nftSignatureWrite,nftTokenDestroy,nftTransferRead,paymentMethodDestroy,paymentMethodRead,paymentMethodSetDefault,adminPriceParametersRead,adminPriceParametersWrite,refundRead,tokenRefresh,authTwoFactor,userActivate,userDataUpdate,userDelete,userDeleteSelf,userEmailVerify,userEmojiList,userInterestDelete,userInterestRead,userInterestWrite,userList,userPubkeysList,userPubkeysWrite,userShow,userWrite,userWriteSelf
    */
    
    enum class GlobalScopes(val value: String){
        @SerializedName( "adminCart:update") adminCartUpdate("adminCart:update"),
        @SerializedName( "adminEmoji:destroy") adminEmojiDestroy("adminEmoji:destroy"),
        @SerializedName( "adminEmoji:load") adminEmojiLoad("adminEmoji:load"),
        @SerializedName( "adminEmoji:register") adminEmojiRegister("adminEmoji:register"),
        @SerializedName( "adminEmoji:transfer") adminEmojiTransfer("adminEmoji:transfer"),
        @SerializedName( "adminEmoji:updateFeatures") adminEmojiUpdateFeatures("adminEmoji:updateFeatures"),
        @SerializedName( "adminEmoji:updateSecureData") adminEmojiUpdateSecureData("adminEmoji:updateSecureData"),
        @SerializedName( "adminEmoji:write") adminEmojiWrite("adminEmoji:write"),
        @SerializedName( "adminFeatureUser:read") adminFeatureUserRead("adminFeatureUser:read"),
        @SerializedName( "adminInvites:write") adminInvitesWrite("adminInvites:write"),
        @SerializedName( "adminInvites:list") adminInvitesList("adminInvites:list"),
        @SerializedName( "adminLootbox:read") adminLootboxRead("adminLootbox:read"),
        @SerializedName( "adminLootbox:write") adminLootboxWrite("adminLootbox:write"),
        @SerializedName( "adminNotifications:write") adminNotificationsWrite("adminNotifications:write"),
        @SerializedName( "adminUser:bypass2fa") adminUserBypass2fa("adminUser:bypass2fa"),
        @SerializedName( "adminUser:load") adminUserLoad("adminUser:load"),
        @SerializedName( "adminUser:loginAs") adminUserLoginAs("adminUser:loginAs"),
        @SerializedName( "adminUser:twoFactorAuthDestroy") adminUserTwoFactorAuthDestroy("adminUser:twoFactorAuthDestroy"),
        @SerializedName( "adminUser:roleUpdate") adminUserRoleUpdate("adminUser:roleUpdate"),
        @SerializedName( "cart:show") cartShow("cart:show"),
        @SerializedName( "cart:update") cartUpdate("cart:update"),
        @SerializedName( "code:delete") codeDelete("code:delete"),
        @SerializedName( "code:read") codeRead("code:read"),
        @SerializedName( "code:write") codeWrite("code:write"),
        @SerializedName( "user:createApiKey") userCreateApiKey("user:createApiKey"),
        @SerializedName( "domainAction:read") domainActionRead("domainAction:read"),
        @SerializedName( "domainEvent:read") domainEventRead("domainEvent:read"),
        @SerializedName( "edition:delete") editionDelete("edition:delete"),
        @SerializedName( "edition:read") editionRead("edition:read"),
        @SerializedName( "edition:write") editionWrite("edition:write"),
        @SerializedName( "emojiGroups:delete") emojiGroupsDelete("emojiGroups:delete"),
        @SerializedName( "emojiGroups:read") emojiGroupsRead("emojiGroups:read"),
        @SerializedName( "emojiGroups:write") emojiGroupsWrite("emojiGroups:write"),
        @SerializedName( "emoji::transfer") emojiTransfer("emoji::transfer"),
        @SerializedName( "feature::delete") featureDelete("feature::delete"),
        @SerializedName( "feature::read") featureRead("feature::read"),
        @SerializedName( "feature::write") featureWrite("feature::write"),
        @SerializedName( "lootbox:use") lootboxUse("lootbox:use"),
        @SerializedName( "order:paymentOverride") orderPaymentOverride("order:paymentOverride"),
        @SerializedName( "order:read") orderRead("order:read"),
        @SerializedName( "order:readSelf") orderReadSelf("order:readSelf"),
        @SerializedName( "order:refund") orderRefund("order:refund"),
        @SerializedName( "order:refundOverride") orderRefundOverride("order:refundOverride"),
        @SerializedName( "order:resendConfirmation") orderResendConfirmation("order:resendConfirmation"),
        @SerializedName( "organization:admin") organizationAdmin("organization:admin"),
        @SerializedName( "organizationCode:admin") organizationCodeAdmin("organizationCode:admin"),
        @SerializedName( "organizationEmoji:list") organizationEmojiList("organizationEmoji:list"),
        @SerializedName( "organizationEmoji:write") organizationEmojiWrite("organizationEmoji:write"),
        @SerializedName( "organizationList:read") organizationListRead("organizationList:read"),
        @SerializedName( "organization:read") organizationRead("organization:read"),
        @SerializedName( "organizationUser:admin") organizationUserAdmin("organizationUser:admin"),
        @SerializedName( "organizationUser:read") organizationUserRead("organizationUser:read"),
        @SerializedName( "organization:write") organizationWrite("organization:write"),
        @SerializedName( "nftSignature:write") nftSignatureWrite("nftSignature:write"),
        @SerializedName( "nftToken:destroy") nftTokenDestroy("nftToken:destroy"),
        @SerializedName( "nftTransfer:read") nftTransferRead("nftTransfer:read"),
        @SerializedName( "paymentMethod:destroy") paymentMethodDestroy("paymentMethod:destroy"),
        @SerializedName( "paymentMethod:read") paymentMethodRead("paymentMethod:read"),
        @SerializedName( "paymentMethod:setDefault") paymentMethodSetDefault("paymentMethod:setDefault"),
        @SerializedName( "adminPriceParameters:read") adminPriceParametersRead("adminPriceParameters:read"),
        @SerializedName( "adminPriceParameters:write") adminPriceParametersWrite("adminPriceParameters:write"),
        @SerializedName( "refund:read") refundRead("refund:read"),
        @SerializedName( "token:refresh") tokenRefresh("token:refresh"),
        @SerializedName( "auth:twoFactor") authTwoFactor("auth:twoFactor"),
        @SerializedName( "user:activate") userActivate("user:activate"),
        @SerializedName( "userData:update") userDataUpdate("userData:update"),
        @SerializedName( "user:delete") userDelete("user:delete"),
        @SerializedName( "user:deleteSelf") userDeleteSelf("user:deleteSelf"),
        @SerializedName( "userEmail:verify") userEmailVerify("userEmail:verify"),
        @SerializedName( "userEmoji:list") userEmojiList("userEmoji:list"),
        @SerializedName( "userInterest:delete") userInterestDelete("userInterest:delete"),
        @SerializedName( "userInterest:read") userInterestRead("userInterest:read"),
        @SerializedName( "userInterest:write") userInterestWrite("userInterest:write"),
        @SerializedName( "user:list") userList("user:list"),
        @SerializedName( "userPubkeys:list") userPubkeysList("userPubkeys:list"),
        @SerializedName( "userPubkeys:write") userPubkeysWrite("userPubkeys:write"),
        @SerializedName( "user:show") userShow("user:show"),
        @SerializedName( "user:write") userWrite("user:write"),
        @SerializedName( "user:writeSelf") userWriteSelf("user:writeSelf");
    }
    /**
    * The role this user has in each organisation. Organisations are currently not used, but are reserved for  future operations.
    * Values: admin,orgController,orgMember,orgOwner,bot,`super`,user
    */
    
    enum class OrganizationRoles(val value: String){
        @SerializedName( "Admin") admin("Admin"),
        @SerializedName( "OrgController") orgController("OrgController"),
        @SerializedName( "OrgMember") orgMember("OrgMember"),
        @SerializedName( "OrgOwner") orgOwner("OrgOwner"),
        @SerializedName( "Bot") bot("Bot"),
        @SerializedName( "Super") `super`("Super"),
        @SerializedName( "User") user("User");
    }
    /**
    * The scopes that are granted to this user for each organisation. Organisations are currently not used, but are  reserved for future operations.
    * Values: adminCartUpdate,adminEmojiDestroy,adminEmojiLoad,adminEmojiRegister,adminEmojiTransfer,adminEmojiUpdateFeatures,adminEmojiUpdateSecureData,adminEmojiWrite,adminFeatureUserRead,adminInvitesWrite,adminInvitesList,adminLootboxRead,adminLootboxWrite,adminNotificationsWrite,adminUserBypass2fa,adminUserLoad,adminUserLoginAs,adminUserTwoFactorAuthDestroy,adminUserRoleUpdate,cartShow,cartUpdate,codeDelete,codeRead,codeWrite,userCreateApiKey,domainActionRead,domainEventRead,editionDelete,editionRead,editionWrite,emojiGroupsDelete,emojiGroupsRead,emojiGroupsWrite,emojiTransfer,featureDelete,featureRead,featureWrite,lootboxUse,orderPaymentOverride,orderRead,orderReadSelf,orderRefund,orderRefundOverride,orderResendConfirmation,organizationAdmin,organizationCodeAdmin,organizationEmojiList,organizationEmojiWrite,organizationListRead,organizationRead,organizationUserAdmin,organizationUserRead,organizationWrite,nftSignatureWrite,nftTokenDestroy,nftTransferRead,paymentMethodDestroy,paymentMethodRead,paymentMethodSetDefault,adminPriceParametersRead,adminPriceParametersWrite,refundRead,tokenRefresh,authTwoFactor,userActivate,userDataUpdate,userDelete,userDeleteSelf,userEmailVerify,userEmojiList,userInterestDelete,userInterestRead,userInterestWrite,userList,userPubkeysList,userPubkeysWrite,userShow,userWrite,userWriteSelf
    */
    
    enum class OrganizationScopes(val value: String){
        @SerializedName( "adminCart:update") adminCartUpdate("adminCart:update"),
        @SerializedName( "adminEmoji:destroy") adminEmojiDestroy("adminEmoji:destroy"),
        @SerializedName( "adminEmoji:load") adminEmojiLoad("adminEmoji:load"),
        @SerializedName( "adminEmoji:register") adminEmojiRegister("adminEmoji:register"),
        @SerializedName( "adminEmoji:transfer") adminEmojiTransfer("adminEmoji:transfer"),
        @SerializedName( "adminEmoji:updateFeatures") adminEmojiUpdateFeatures("adminEmoji:updateFeatures"),
        @SerializedName( "adminEmoji:updateSecureData") adminEmojiUpdateSecureData("adminEmoji:updateSecureData"),
        @SerializedName( "adminEmoji:write") adminEmojiWrite("adminEmoji:write"),
        @SerializedName( "adminFeatureUser:read") adminFeatureUserRead("adminFeatureUser:read"),
        @SerializedName( "adminInvites:write") adminInvitesWrite("adminInvites:write"),
        @SerializedName( "adminInvites:list") adminInvitesList("adminInvites:list"),
        @SerializedName( "adminLootbox:read") adminLootboxRead("adminLootbox:read"),
        @SerializedName( "adminLootbox:write") adminLootboxWrite("adminLootbox:write"),
        @SerializedName( "adminNotifications:write") adminNotificationsWrite("adminNotifications:write"),
        @SerializedName( "adminUser:bypass2fa") adminUserBypass2fa("adminUser:bypass2fa"),
        @SerializedName( "adminUser:load") adminUserLoad("adminUser:load"),
        @SerializedName( "adminUser:loginAs") adminUserLoginAs("adminUser:loginAs"),
        @SerializedName( "adminUser:twoFactorAuthDestroy") adminUserTwoFactorAuthDestroy("adminUser:twoFactorAuthDestroy"),
        @SerializedName( "adminUser:roleUpdate") adminUserRoleUpdate("adminUser:roleUpdate"),
        @SerializedName( "cart:show") cartShow("cart:show"),
        @SerializedName( "cart:update") cartUpdate("cart:update"),
        @SerializedName( "code:delete") codeDelete("code:delete"),
        @SerializedName( "code:read") codeRead("code:read"),
        @SerializedName( "code:write") codeWrite("code:write"),
        @SerializedName( "user:createApiKey") userCreateApiKey("user:createApiKey"),
        @SerializedName( "domainAction:read") domainActionRead("domainAction:read"),
        @SerializedName( "domainEvent:read") domainEventRead("domainEvent:read"),
        @SerializedName( "edition:delete") editionDelete("edition:delete"),
        @SerializedName( "edition:read") editionRead("edition:read"),
        @SerializedName( "edition:write") editionWrite("edition:write"),
        @SerializedName( "emojiGroups:delete") emojiGroupsDelete("emojiGroups:delete"),
        @SerializedName( "emojiGroups:read") emojiGroupsRead("emojiGroups:read"),
        @SerializedName( "emojiGroups:write") emojiGroupsWrite("emojiGroups:write"),
        @SerializedName( "emoji::transfer") emojiTransfer("emoji::transfer"),
        @SerializedName( "feature::delete") featureDelete("feature::delete"),
        @SerializedName( "feature::read") featureRead("feature::read"),
        @SerializedName( "feature::write") featureWrite("feature::write"),
        @SerializedName( "lootbox:use") lootboxUse("lootbox:use"),
        @SerializedName( "order:paymentOverride") orderPaymentOverride("order:paymentOverride"),
        @SerializedName( "order:read") orderRead("order:read"),
        @SerializedName( "order:readSelf") orderReadSelf("order:readSelf"),
        @SerializedName( "order:refund") orderRefund("order:refund"),
        @SerializedName( "order:refundOverride") orderRefundOverride("order:refundOverride"),
        @SerializedName( "order:resendConfirmation") orderResendConfirmation("order:resendConfirmation"),
        @SerializedName( "organization:admin") organizationAdmin("organization:admin"),
        @SerializedName( "organizationCode:admin") organizationCodeAdmin("organizationCode:admin"),
        @SerializedName( "organizationEmoji:list") organizationEmojiList("organizationEmoji:list"),
        @SerializedName( "organizationEmoji:write") organizationEmojiWrite("organizationEmoji:write"),
        @SerializedName( "organizationList:read") organizationListRead("organizationList:read"),
        @SerializedName( "organization:read") organizationRead("organization:read"),
        @SerializedName( "organizationUser:admin") organizationUserAdmin("organizationUser:admin"),
        @SerializedName( "organizationUser:read") organizationUserRead("organizationUser:read"),
        @SerializedName( "organization:write") organizationWrite("organization:write"),
        @SerializedName( "nftSignature:write") nftSignatureWrite("nftSignature:write"),
        @SerializedName( "nftToken:destroy") nftTokenDestroy("nftToken:destroy"),
        @SerializedName( "nftTransfer:read") nftTransferRead("nftTransfer:read"),
        @SerializedName( "paymentMethod:destroy") paymentMethodDestroy("paymentMethod:destroy"),
        @SerializedName( "paymentMethod:read") paymentMethodRead("paymentMethod:read"),
        @SerializedName( "paymentMethod:setDefault") paymentMethodSetDefault("paymentMethod:setDefault"),
        @SerializedName( "adminPriceParameters:read") adminPriceParametersRead("adminPriceParameters:read"),
        @SerializedName( "adminPriceParameters:write") adminPriceParametersWrite("adminPriceParameters:write"),
        @SerializedName( "refund:read") refundRead("refund:read"),
        @SerializedName( "token:refresh") tokenRefresh("token:refresh"),
        @SerializedName( "auth:twoFactor") authTwoFactor("auth:twoFactor"),
        @SerializedName( "user:activate") userActivate("user:activate"),
        @SerializedName( "userData:update") userDataUpdate("userData:update"),
        @SerializedName( "user:delete") userDelete("user:delete"),
        @SerializedName( "user:deleteSelf") userDeleteSelf("user:deleteSelf"),
        @SerializedName( "userEmail:verify") userEmailVerify("userEmail:verify"),
        @SerializedName( "userEmoji:list") userEmojiList("userEmoji:list"),
        @SerializedName( "userInterest:delete") userInterestDelete("userInterest:delete"),
        @SerializedName( "userInterest:read") userInterestRead("userInterest:read"),
        @SerializedName( "userInterest:write") userInterestWrite("userInterest:write"),
        @SerializedName( "user:list") userList("user:list"),
        @SerializedName( "userPubkeys:list") userPubkeysList("userPubkeys:list"),
        @SerializedName( "userPubkeys:write") userPubkeysWrite("userPubkeys:write"),
        @SerializedName( "user:show") userShow("user:show"),
        @SerializedName( "user:write") userWrite("user:write"),
        @SerializedName( "user:writeSelf") userWriteSelf("user:writeSelf");
    }
    /**
    * The role assigned to this user. Roles grant authority to user accounts to perform certain actions.
    * Values: admin,orgController,orgMember,orgOwner,bot,`super`,user
    */
    
    enum class Role(val value: kotlin.String){
        @SerializedName( "Admin") admin("Admin"),
        @SerializedName( "OrgController") orgController("OrgController"),
        @SerializedName( "OrgMember") orgMember("OrgMember"),
        @SerializedName( "OrgOwner") orgOwner("OrgOwner"),
        @SerializedName( "Bot") bot("Bot"),
        @SerializedName( "Super") `super`("Super"),
        @SerializedName( "User") user("User");
    }
}

