/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models


import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param currentUser 
 * @param editions 
 * @param extendedList 
 * @param incomingTransfers 
 * @param outgoingTransfers 
 * @param wallets 
 * @param everflowTransactionId 
 * @param sidebar 
 */

data class LoadUser (
    @SerializedName( "current_user")
    val currentUser: LoadUserCurrentUser,
    @SerializedName( "editions")
    val editions: kotlin.collections.List<kotlin.Long>,
    @SerializedName( "extended_list")
    val extendedList: kotlin.collections.List<LoadUserExtendedList>,
    @SerializedName( "incoming_transfers")
    val incomingTransfers: kotlin.collections.List<ListOfDisplayTransferRequestData>,
    @SerializedName( "outgoing_transfers")
    val outgoingTransfers: LoadUserOutgoingTransfers,
    @SerializedName( "wallets")
    val wallets: kotlin.collections.List<LoadUserWallets>,
    @SerializedName( "everflow_transaction_id")
    val everflowTransactionId: kotlin.String? = null,
    @SerializedName( "sidebar")
    val sidebar: kotlin.Any? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

