/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models

import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param animationUrl 
 * @param attributes 
 * @param description 
 * @param externalLink 
 * @param image 
 * @param name 
 */

data class Metadata (
    @Json(name = "animation_url")
    val animationUrl: kotlin.String,
    @Json(name = "attributes")
    val attributes: kotlin.collections.List<MetadataAttributes>,
    @Json(name = "description")
    val description: kotlin.String,
    @Json(name = "external_link")
    val externalLink: kotlin.String,
    @Json(name = "image")
    val image: kotlin.String,
    @Json(name = "name")
    val name: kotlin.String
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

