/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models



import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param id 
 * @param paymentType 
 * @param brand 
 * @param country 
 * @param expMonth 
 * @param expYear 
 * @param last4 
 */

data class PaymentMethod (
    @SerializedName( "id")
    val id: kotlin.String,
    @SerializedName( "payment_type")
    val paymentType: kotlin.String,
    @SerializedName( "brand")
    val brand: kotlin.String? = null,
    @SerializedName( "country")
    val country: kotlin.String? = null,
    @SerializedName( "exp_month")
    val expMonth: kotlin.Int? = null,
    @SerializedName( "exp_year")
    val expYear: kotlin.Int? = null,
    @SerializedName( "last4")
    val last4: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

