/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param nonce Schnorr signature nonce as a hex string
 * @param pubkey Public key to authorize usage of a code
 * @param signature Schnorr signature as a hex with alternate_id as a challenge
 * @param trackingData Custom tracking data to be associated with a purchase
 */

data class RandomYatActivateBody (
    /* Schnorr signature nonce as a hex string */
    @field:Json(name = "nonce")
    val nonce: kotlin.String,
    /* Public key to authorize usage of a code */
    @field:Json(name = "pubkey")
    val pubkey: kotlin.String,
    /* Schnorr signature as a hex with alternate_id as a challenge */
    @field:Json(name = "signature")
    val signature: kotlin.String,
    /* Custom tracking data to be associated with a purchase */
    @field:Json(name = "tracking_data")
    val trackingData: kotlin.Any? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

