/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package yat.android.sdk.models



import com.google.gson.annotations.SerializedName
import java.io.Serializable

/**
 * 
 * @param currencies 
 * @param returnLink 
 * @param logo 
 * @param logoSmall 
 * @param logoThumbnail 
 * @param requiresEmail 
 */

data class UpdateOrganizationBranding (
    @SerializedName( "currencies")
    val currencies: kotlin.collections.List<kotlin.String>,
    @SerializedName( "return_link")
    val returnLink: kotlin.String,
    @SerializedName( "logo")
    val logo: kotlin.String? = null,
    @SerializedName( "logo_small")
    val logoSmall: kotlin.String? = null,
    @SerializedName( "logo_thumbnail")
    val logoThumbnail: kotlin.String? = null,
    @SerializedName( "requires_email")
    val requiresEmail: kotlin.Boolean? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

