/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param default Make this method default
 * @param provider Two factor authentication backend
 * @param phone Phone number required for `SMS` provider
 */

data class Enable2FABody (
    /* Make this method default */
    @Json(name = "default")
    val default: kotlin.Boolean,
    /* Two factor authentication backend */
    @Json(name = "provider")
    val provider: Enable2FABody.Provider,
    /* Phone number required for `SMS` provider */
    @Json(name = "phone")
    val phone: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
    * Two factor authentication backend
    * Values: googleAuthenticator,sMS
    */
    
    enum class Provider(val value: kotlin.String){
        @Json(name = "GoogleAuthenticator") googleAuthenticator("GoogleAuthenticator"),
        @Json(name = "SMS") sMS("SMS");
    }
}

