/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * Paging information
 * @param dir 
 * @param limit 
 * @param page 
 * @param sort 
 * @param tags 
 * @param total 
 */

data class ListOfCodeAvailabilityPaging (
    @Json(name = "dir")
    val dir: ListOfCodeAvailabilityPaging.Dir,
    @Json(name = "limit")
    val limit: kotlin.Int,
    @Json(name = "page")
    val page: kotlin.Int,
    @Json(name = "sort")
    val sort: kotlin.String,
    @Json(name = "tags")
    val tags: kotlin.collections.Map<kotlin.String, kotlin.Any>,
    @Json(name = "total")
    val total: kotlin.Long
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
    * 
    * Values: asc,desc
    */
    
    enum class Dir(val value: kotlin.String){
        @Json(name = "Asc") asc("Asc"),
        @Json(name = "Desc") desc("Desc");
    }
}

