/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param lootBoxTypeId The id of the loot box type to generate
 * @param numBoxes The number of loot boxes to generate in this sample
 */

data class LootBoxGenerationRequest (
    /* The id of the loot box type to generate */
    @Json(name = "loot_box_type_id")
    val lootBoxTypeId: java.util.UUID,
    /* The number of loot boxes to generate in this sample */
    @Json(name = "num_boxes")
    val numBoxes: kotlin.Long
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

