/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param createdAt 
 * @param currencies 
 * @param name 
 * @param organizationId 
 * @param requiresEmail 
 * @param returnLink 
 * @param updatedAt 
 * @param logo 
 * @param logoSmall 
 * @param logoThumbnail 
 */

data class OrganizationBranding (
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,
    @Json(name = "currencies")
    val currencies: kotlin.collections.List<kotlin.String>,
    @Json(name = "name")
    val name: kotlin.String,
    @Json(name = "organization_id")
    val organizationId: java.util.UUID,
    @Json(name = "requires_email")
    val requiresEmail: kotlin.Boolean,
    @Json(name = "return_link")
    val returnLink: kotlin.String,
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,
    @Json(name = "logo")
    val logo: kotlin.String? = null,
    @Json(name = "logo_small")
    val logoSmall: kotlin.String? = null,
    @Json(name = "logo_thumbnail")
    val logoThumbnail: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

