/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param id 
 * @param paymentType 
 * @param brand 
 * @param country 
 * @param expMonth 
 * @param expYear 
 * @param last4 
 */

data class PaymentMethod (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "payment_type")
    val paymentType: kotlin.String,
    @Json(name = "brand")
    val brand: kotlin.String? = null,
    @Json(name = "country")
    val country: kotlin.String? = null,
    @Json(name = "exp_month")
    val expMonth: kotlin.Int? = null,
    @Json(name = "exp_year")
    val expYear: kotlin.Int? = null,
    @Json(name = "last4")
    val last4: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

