/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param service `ProxyService` type
 * @param data The data to pass through to the proxied service
 */

data class ProxyCallParameters (
    /* `ProxyService` type */
    @Json(name = "service")
    val service: ProxyCallParameters.Service,
    /* The data to pass through to the proxied service */
    @Json(name = "data")
    val data: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
    * `ProxyService` type
    * Values: echo,scraper
    */
    
    enum class Service(val value: kotlin.String){
        @Json(name = "Echo") echo("Echo"),
        @Json(name = "Scraper") scraper("Scraper");
    }
}

