/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param currentPassword Optional: Current password, must be provided if one exists
 * @param email Optional: Email
 * @param firstName Optional: First name
 * @param lastName Optional: Last name
 * @param password Optional: User password
 */

data class UpdateUserParameters (
    /* Optional: Current password, must be provided if one exists */
    @Json(name = "current_password")
    val currentPassword: kotlin.String? = null,
    /* Optional: Email */
    @Json(name = "email")
    val email: kotlin.String? = null,
    /* Optional: First name */
    @Json(name = "first_name")
    val firstName: kotlin.String? = null,
    /* Optional: Last name */
    @Json(name = "last_name")
    val lastName: kotlin.String? = null,
    /* Optional: User password */
    @Json(name = "password")
    val password: kotlin.String? = null
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

}

