/**
* Emoji ID API server
* Emoji ID is a directory service that associates almost any type of structured data with a short, memorable identifier the emoji id.
*
* The version of the OpenAPI document: 0.2.262
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.yatlabs.yat.models


import com.squareup.moshi.Json
import java.io.Serializable

/**
 * 
 * @param signature 
 * @param source 
 */

data class WalletSyncRequest (
    @Json(name = "signature")
    val signature: kotlin.String,
    @Json(name = "source")
    val source: WalletSyncRequest.Source
) : Serializable {
    companion object {
        private const val serialVersionUID: Long = 123
    }

    /**
    * 
    * Values: mint,dashboard
    */
    
    enum class Source(val value: kotlin.String){
        @Json(name = "Mint") mint("Mint"),
        @Json(name = "Dashboard") dashboard("Dashboard");
    }
}

